library(dplyr)
data <- read.table("household_power_consumption.txt",sep=";",header = TRUE, na.strings = "?")
doc <- tbl_df(data)
doc <- mutate(doc, Date = as.character(doc$Date))
doc <- filter(doc, doc$Date %in% c("1/2/2007","2/2/2007"))
DateTime = as.POSIXct(paste(doc$Date, doc$Time), format="%d/%m/%Y %H:%M:%S")
plot(DateTime,doc$Sub_metering_1,type = "n",xlab = "",ylab = "Energy sub metering")
lines(DateTime,doc$Sub_metering_1,type = "l",col = "Black")
lines(DateTime,doc$Sub_metering_2,type = "l",col ="Red")
lines(DateTime,doc$Sub_metering_3,type = "l",col = "Blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("Black","Red","Blue"),lty = 1)
dev.copy(png,file = "plot3.png")
dev.off()