library(dplyr)
data <- read.table("household_power_consumption.txt",sep=";",header = TRUE, na.strings = "?")
doc <- tbl_df(data)
doc <- mutate(doc, Date = as.character(doc$Date))
doc <- filter(doc, doc$Date %in% c("1/2/2007","2/2/2007"))
DateTime = as.POSIXct(paste(doc$Date, doc$Time), format="%d/%m/%Y %H:%M:%S")
plot(DateTime,doc$Global_active_power,type = "n",xlab = "",ylab = "Global Active Power(Kilowatts)")
lines(DateTime,doc$Global_active_power,type = "l")
dev.copy(png,file = "plot2.png")
dev.off()